# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Spotify' do
  pod 'Kingfisher', '~> 7.0'
  pod 'IQKeyboardManagerSwift'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  # Pods for Spotify

  target 'SpotifyTests' do
    pod 'Kingfisher', '~> 7.0'
  end

end
